### ISSUE TITLE
Experimental reviewer recommendations - slow & more instructions needed

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss-papers#1635]
I ran the first cell, then changed the XXXXX in the second to the paper number I'm interested in (02532) and ran that cell - everything seems fine.  (maybe make it clear that you need this to match the number of the paper in the filename, including the leading zero)

Then I ran the third cell - this took 5-10 minutes.  Probably some message is needed that it will take a long time. Or even better, add a progress widget.

When I run the 4th cell, I get a file not found error. If I need to upload a paper, there should be instructions for how to do this, including where to upload it.  Does it just go in the same directory as the notebook?
It seems like the answer is yes.

Ok, now it worked.

**Comment by danielskatz** [comment]
maybe at the top, provide a set of instructions (step by step) of what needs to be done:
1. change cell 2 to the including the paper number, with leading zeros, to match the number of the pdf
2. upload the paper pdf
3. run the notebook

**Comment by arfon** [comment]
Thanks @danielskatz - these updates were made by @elizabeth-pugliese in #1637.

<img width="1050" alt="Screen Shot 2020-08-17 at 10 56 41" src="https://user-images.githubusercontent.com/4483/90383714-6f866f00-e078-11ea-85e4-61410fecd1bd.png">
