### ISSUE TITLE
experimental reviewer matching - more reviewer info needed

### ISSUE THREAD

**Issue by danielskatz** [openjournals/joss-papers#1636]
At the end, when the list of reviewers is generated, it would be great to also pull in review stats for them.  Are they currently reviewing any JOSS papers?  If so, how many?  How many have they reviewed in the last 3 months?  Last year? Ever?

**Comment by arfon** [comment]
Oh, sorry. I just copied the screenshot into the wrong issue. 

Thanks to @elizabeth-pugliese - this information is now in the recommendations:

<img width="1050" alt="Screen Shot 2020-08-17 at 10 56 41" src="https://user-images.githubusercontent.com/4483/90383788-8b8a1080-e078-11ea-80c2-8fc25885c791.png">
