### ISSUE TITLE
Name

### ISSUE THREAD

**Issue by salabim** [openjournals/joss-papers#7]
My last name is ‘van der Ham’ not ‘Ham’. Please correct.

**Comment by arfon** [comment]
Please link to the paper where this is incorrect.

**Comment by salabim** [comment]
Do I need to take any action on this? If so, please clarify.


Ruud van der Ham
*rt.van.der.ham@gmail.com <rt.van.der.ham@gmail.com>*

**Comment by arfon** [comment]
> Do I need to take any action on this? If so, please clarify.

Yes. Please link to your paper either by DOI or on the JOSS site.

**Comment by salabim** [comment]
Sorry, But can you explain this to me?


Ruud van der Ham
*rt.van.der.ham@gmail.com <rt.van.der.ham@gmail.com>*

**Comment by arfon** [comment]
I'm struggling to be more explicit. You mentioned that your name is wrong in your paper. _Which_ paper. Please share a URL/link/*anything* that will help me understand which paper you are talking about.

**Comment by salabim** [comment]
The spelling of my name was about the salabim article, where my name is
spelt as *Ham, Ruud*. But my name is actually *van der Ham. Ruud*. Not a
big thing, but if that could be corrected that would be nice.


Ruud van der Ham
*rt.van.der.ham@gmail.com <rt.van.der.ham@gmail.com>*

**Comment by danielskatz** [comment]
@arfon - this is an issue with how the surname is picked up in https://github.com/salabim/salabim/blob/master/paper.md and inserted in the footer of the paper.

**Comment by danielskatz** [comment]
The related review issue is https://github.com/openjournals/joss-reviews/issues/767

**Comment by arfon** [comment]
> @arfon - this is an issue with how the surname is picked up in https://github.com/salabim/salabim/blob/master/paper.md and inserted in the footer of the paper.

Understood. @salabim - please remind us in openjournals/joss-reviews#767 to fix this issue. I have to manually fix this when we accept the paper.
