### ISSUE TITLE
Regenerate PDF of paper 118 - Multilocus sequence typing by blast from de novo assemblies against PubMLST

### ISSUE THREAD

**Issue by andrewjpage** [openjournals/joss-papers#8]
Hi,
I was wondering if it would be possible to regenerate the PDF of paper 00118 (Multilocus sequence typing by blast from de novo assemblies against PubMLST) as I had a typo in a surname of one of the authors I referenced?

The paper:
http://joss.theoj.org/papers/0b801d23613c9b626c2b6028f8c14056
https://www.theoj.org/joss-papers/joss.00118/10.21105.joss.00118.pdf

The typo fix to paper.bib:
https://github.com/sanger-pathogens/mlst_check/commit/2f8457e7c84f585b8c8a835978f9ae461bab113e

And the paper source itself:
https://github.com/sanger-pathogens/mlst_check/blob/master/paper.md
https://github.com/sanger-pathogens/mlst_check/blob/master/paper.bib

Thanks a million, its a brilliant journal and I really appreciate all the hard work thats gone into it.
Andrew

**Comment by arfon** [comment]
OK great. That should be updated on the site in the next few hours.
